"""
Curated catalog of every loggable variable in the USV system.

Each field describes:
  - id     : stable snake_case identifier (used in CsvLoggerConfig.fields)
  - label  : human-readable label for the GUI
  - topic  : ZMQ topic that carries the source payload (Topics enum value)
  - path   : dot-path inside the payload dict (e.g. "lat", "config.cruise_speed_kn")
  - unit   : display unit
  - dtype  : "float" | "int" | "str" | "bool"

The catalog is grouped for UI display. Group order is preserved.

The field id ``timestamp_utc`` is special: it is always prepended as the first
CSV column / first JSON key and is generated by LoggerProcess itself (ISO-8601
with milliseconds, UTC), so it never appears in this catalog.
"""

from src.core.messaging import Topics

T_GNSS = Topics.SENSOR_GNSS.value
T_IMU = Topics.SENSOR_IMU.value
T_BAT = Topics.SENSOR_BATTERY.value
T_STAT = Topics.SENSOR_STATUS.value
T_STATE = Topics.STATE_ESTIMATION.value
T_CTRL = Topics.CONTROL_CMD.value
T_DBG = Topics.CONTROL_DEBUG.value
T_SYS = Topics.SYSTEM_STATUS.value
T_CMD = Topics.COMMAND_USER.value
T_SIM = Topics.SIM_STATUS.value
T_LINK = Topics.COMMS_LINK.value
T_MON = Topics.SYSTEM_MONITOR.value


def _f(id_, label, topic, path, unit="", dtype="float"):
    return {"id": id_, "label": label, "topic": topic, "path": path,
            "unit": unit, "dtype": dtype}


LOG_FIELD_GROUPS = [
    {
        "id": "usv_status",
        "label": "USV Status",
        "fields": [
            _f("is_armed",          "Armed",              T_SYS, "is_armed",          "",   "bool"),
            _f("vehicle_mode",      "Vehicle Mode",       T_SYS, "mode",              "",   "str"),
            _f("sim_mode",          "Sim/Real Mode",      T_SYS, "sim_mode",          "",   "str"),
            _f("system_status",     "System Status",      T_SYS, "system_status",     "",   "str"),
            _f("station_active",    "Station Active",     T_SYS, "station_active",    "",   "bool"),
            _f("wp_route_active",   "WP Route Active",    T_SYS, "wp_route_active",   "",   "bool"),
            _f("wp_route_direction","WP Route Direction", T_SYS, "wp_route_direction","",   "str"),
            _f("wp_route_completion","WP Route Completion",T_SYS,"wp_route_completion","",  "str"),
            _f("gnss_fix_type_sys", "GNSS Fix Type (sys)",T_SYS, "gnss_fix_type",     "",   "int"),
        ],
    },
    {
        "id": "position",
        "label": "Position / Navigation (EKF)",
        "fields": [
            _f("state_lat",         "Latitude",           T_STATE, "lat",     "deg",  "float"),
            _f("state_lon",         "Longitude",          T_STATE, "lon",     "deg",  "float"),
            _f("state_altitude",    "Altitude",           T_STATE, "altitude","m",    "float"),
            _f("state_speed",       "Speed",              T_STATE, "speed",   "m/s",  "float"),
            _f("state_course",      "Course",             T_STATE, "course",  "deg",  "float"),
            _f("state_heading",     "Heading",            T_STATE, "heading", "deg",  "float"),
            _f("state_roll_crp",    "Roll (CRP)",         T_STATE, "roll_crp",  "deg",  "float"),
            _f("state_pitch_crp",   "Pitch (CRP)",        T_STATE, "pitch_crp", "deg",  "float"),
            _f("state_yaw_crp",     "Yaw (CRP)",          T_STATE, "yaw_crp",   "deg",  "float"),
            _f("state_wx_crp",      "Roll Rate (CRP)",    T_STATE, "wx_crp",    "deg/s","float"),
            _f("state_wy_crp",      "Pitch Rate (CRP)",   T_STATE, "wy_crp",    "deg/s","float"),
            _f("state_wz_crp",      "Yaw Rate (CRP)",     T_STATE, "wz_crp",    "deg/s","float"),
            _f("state_accx_crp",    "Accel X (CRP)",      T_STATE, "accx_crp",  "m/s²", "float"),
            _f("state_accy_crp",    "Accel Y (CRP)",      T_STATE, "accy_crp",  "m/s²", "float"),
            _f("state_accz_crp",    "Accel Z (CRP)",      T_STATE, "accz_crp",  "m/s²", "float"),
            _f("state_mag_heading_crp","Mag Heading (CRP)",T_STATE,"mag_heading_crp","deg","float"),
            _f("state_heading_status","Heading Status",   T_STATE, "heading_status","","str"),
            _f("state_source",      "Source",             T_STATE, "source",  "",     "str"),
        ],
    },
    {
        "id": "gnss",
        "label": "GNSS (raw sensor)",
        "fields": [
            _f("gnss_lat",          "Latitude",           T_GNSS, "lat",            "deg",  "float"),
            _f("gnss_lon",          "Longitude",          T_GNSS, "lon",            "deg",  "float"),
            _f("gnss_alt",          "Altitude (AMSL)",    T_GNSS, "alt",            "m",    "float"),
            _f("gnss_fix_type",     "Fix Type",           T_GNSS, "fix_type",       "",     "int"),
            _f("gnss_num_sats",     "Satellites",         T_GNSS, "num_satellites", "",     "int"),
            _f("gnss_hdop",         "HDOP",               T_GNSS, "hdop",           "",     "float"),
            _f("gnss_vdop",         "VDOP",               T_GNSS, "vdop",           "",     "float"),
            _f("gnss_heading",      "Heading (THS)",      T_GNSS, "heading",        "deg",  "float"),
            _f("gnss_heading_status","Heading Status",    T_GNSS, "heading_status", "",     "str"),
            _f("gnss_cog",          "COG",                T_GNSS, "cog",            "deg",  "float"),
            _f("gnss_sog_knots",    "SOG",                T_GNSS, "sog_knots",      "kn",   "float"),
            _f("gnss_sog_kmh",      "SOG",                T_GNSS, "sog_kmh",        "km/h", "float"),
            _f("gnss_utc_time",     "UTC Time",           T_GNSS, "utc_time",       "",     "str"),
            _f("gnss_utc_date",     "UTC Date",           T_GNSS, "utc_date",       "",     "str"),
            _f("gnss_source",       "Source",             T_GNSS, "source",         "",     "str"),
        ],
    },
    {
        "id": "imu",
        "label": "IMU",
        "fields": [
            _f("imu_roll_raw",      "Roll (raw)",         T_IMU, "roll_raw",    "deg",   "float"),
            _f("imu_pitch_raw",     "Pitch (raw)",        T_IMU, "pitch_raw",   "deg",   "float"),
            _f("imu_yaw_raw",       "Yaw (raw)",          T_IMU, "yaw_raw",     "deg",   "float"),
            _f("imu_ax_raw",        "Accel X (raw)",      T_IMU, "ax_raw",      "m/s²",  "float"),
            _f("imu_ay_raw",        "Accel Y (raw)",      T_IMU, "ay_raw",      "m/s²",  "float"),
            _f("imu_az_raw",        "Accel Z (raw)",      T_IMU, "az_raw",      "m/s²",  "float"),
            _f("imu_wx_raw",        "Gyro X (raw)",       T_IMU, "wx_raw",      "deg/s", "float"),
            _f("imu_wy_raw",        "Gyro Y (raw)",       T_IMU, "wy_raw",      "deg/s", "float"),
            _f("imu_wz_raw",        "Gyro Z (raw)",       T_IMU, "wz_raw",      "deg/s", "float"),
            _f("imu_mx_raw",        "Mag X (raw)",        T_IMU, "mx_raw",      "",      "float"),
            _f("imu_my_raw",        "Mag Y (raw)",        T_IMU, "my_raw",      "",      "float"),
            _f("imu_mz_raw",        "Mag Z (raw)",        T_IMU, "mz_raw",      "",      "float"),
            _f("imu_temp",          "Temperature",        T_IMU, "temp",        "°C",    "float"),
            _f("imu_mag_heading_raw","Mag Heading (raw)", T_IMU, "mag_heading_raw","deg","float"),
            _f("imu_source",        "Source",             T_IMU, "source",      "",      "str"),
        ],
    },
    {
        "id": "gnc",
        "label": "GNC (control debug)",
        "fields": [
            _f("gnc_target_heading","Target Heading",     T_DBG, "target_heading",  "deg", "float"),
            _f("gnc_heading_error", "Heading Error",      T_DBG, "heading_error",   "deg", "float"),
            _f("gnc_cte",           "Cross-Track Error",  T_DBG, "cross_track_error","m",  "float"),
            _f("gnc_surge_vel",     "Surge Velocity",     T_DBG, "surge_vel",       "m/s", "float"),
            _f("gnc_sway_vel",      "Sway Velocity",      T_DBG, "sway_vel",        "m/s", "float"),
            _f("gnc_surge_acc",     "Surge Accel",        T_DBG, "surge_acc",       "m/s²","float"),
            _f("gnc_sway_acc",      "Sway Accel",         T_DBG, "sway_acc",        "m/s²","float"),
            _f("gnc_tau_x_eff",     "τx Effective",       T_DBG, "tau_x_eff",       "N",   "float"),
            _f("gnc_tau_x_cruise",  "τx Cruise",          T_DBG, "tau_x_cruise",    "N",   "float"),
            _f("gnc_v_cruise",      "Cruise Speed",       T_DBG, "v_cruise",        "m/s", "float"),
            _f("gnc_wp_index",      "WP Index",           T_DBG, "wp_index",        "",    "int"),
            _f("gnc_dist_to_wp",    "Distance to WP",     T_DBG, "dist_to_wp",      "m",   "float"),
            _f("gnc_ref_speed_kn",  "Reference Speed",    T_DBG, "ref_speed_kn",    "kn",  "float"),
            _f("gnc_ett_next_wp",   "ETT next WP",        T_DBG, "ett_next_wp",     "s",   "float"),
            _f("gnc_eta_next_wp",   "ETA next WP",        T_DBG, "eta_next_wp",     "ts",  "float"),
            _f("gnc_ett_route_end", "ETT route end",      T_DBG, "ett_route_end",   "s",   "float"),
            _f("gnc_eta_route_end", "ETA route end",      T_DBG, "eta_route_end",   "ts",  "float"),
            _f("gnc_kp_m",          "KP (chainage)",      T_DBG, "kp_m",            "m",   "float"),
        ],
    },
    {
        "id": "control_cmd",
        "label": "Motor Commands",
        "fields": [
            _f("motor_port",        "Motor Port",         T_CTRL, "port_pct",      "%",     "float"),
            _f("motor_starboard",   "Motor Starboard",    T_CTRL, "starboard_pct", "%",     "float"),
            _f("motor_n1_rads",     "Motor n1",           T_CTRL, "n1_rads",       "rad/s", "float"),
            _f("motor_n2_rads",     "Motor n2",           T_CTRL, "n2_rads",       "rad/s", "float"),
            _f("motor_source",      "Cmd Source",         T_CTRL, "source",        "",      "str"),
        ],
    },
    {
        "id": "wp_route",
        "label": "WP Route / Station",
        "fields": [
            _f("station_wp_lat",       "Station WP Lat",  T_SYS, "station_wp.lat", "deg", "float"),
            _f("station_wp_lon",       "Station WP Lon",  T_SYS, "station_wp.lon", "deg", "float"),
            _f("station_reaching_r",   "Station Reach R", T_SYS, "station_reaching_radius","m","float"),
            _f("station_radius",       "Station Radius",  T_SYS, "station_radius", "m",   "float"),
            _f("home_wp_lat",          "Home WP Lat",     T_SYS, "home_wp.lat",    "deg", "float"),
            _f("home_wp_lon",          "Home WP Lon",     T_SYS, "home_wp.lon",    "deg", "float"),
        ],
    },
    {
        "id": "battery",
        "label": "Battery / Power",
        "fields": [
            _f("bat_voltage",       "Voltage",            T_BAT, "voltage",           "V",   "float"),
            _f("bat_current",       "Current",            T_BAT, "current",           "A",   "float"),
            _f("bat_power",         "Power",              T_BAT, "power",             "W",   "float"),
            _f("bat_energy_wh",     "Energy (HW)",        T_BAT, "energy_wh",         "Wh",  "int"),
            _f("bat_level_pct",     "Level",              T_BAT, "level_pct",         "%",   "float"),
            _f("bat_capacity_wh",   "Capacity",           T_BAT, "capacity_wh",       "Wh",  "float"),
            _f("bat_accumulated_wh","Consumed (SW)",      T_BAT, "accumulated_wh",    "Wh",  "float"),
            _f("bat_measurement_start","Measurement Start",T_BAT,"measurement_start", "ts",  "float"),
            _f("bat_high_alarm",    "High V Alarm",       T_BAT, "high_voltage_alarm","",    "int"),
            _f("bat_low_alarm",     "Low V Alarm",        T_BAT, "low_voltage_alarm", "",    "int"),
        ],
    },
    {
        "id": "manual",
        "label": "Manual Control / Commands",
        "fields": [
            _f("cmd_type",          "Last Command Type",  T_CMD, "type",                "", "str"),
            _f("cmd_seq",           "Last Command Seq",   T_CMD, "seq",                 "", "int"),
            _f("manual_throttle",   "Manual Throttle",    T_CMD, "payload.throttle",    "", "float"),
            _f("manual_steering",   "Manual Steering",    T_CMD, "payload.steering",    "", "float"),
        ],
    },
    {
        "id": "failsafe",
        "label": "Failsafe Config",
        "fields": [
            _f("fs_min_battery_pct","Min Battery",        T_SYS, "failsafe_config.min_battery_pct","%","float"),
            _f("fs_min_gnss_fix",   "Min GNSS Fix",       T_SYS, "failsafe_config.min_gnss_fix",   "", "int"),
            _f("fs_comm_timeout",   "Comm Timeout",       T_SYS, "failsafe_config.comm_timeout",   "s","float"),
            _f("fs_comm_action",    "Comm Action",        T_SYS, "failsafe_config.comm_action",    "", "str"),
            _f("fs_ins_timeout",    "INS Timeout",        T_SYS, "failsafe_config.ins_timeout",    "s","float"),
            _f("fs_ins_action",     "INS Action",         T_SYS, "failsafe_config.ins_action",     "", "str"),
        ],
    },
    {
        "id": "rt_sim",
        "label": "RT Simulation",
        "fields": [
            _f("sim_running",       "Sim Running",        T_SIM, "running",          "",  "bool"),
            _f("sim_elapsed_time",  "Sim Elapsed",        T_SIM, "elapsed_time",     "s", "float"),
            _f("sim_total_time",    "Sim Total",          T_SIM, "total_time",       "s", "float"),
            _f("sim_completion",    "Completion Mode",    T_SIM, "completion_mode",  "",  "str"),
            _f("sim_gnss_mode",     "GNSS Mode",          T_SIM, "gnss_mode",        "",  "str"),
            _f("sim_current_wp",    "Current WP",         T_SIM, "current_wp",       "",  "int"),
            _f("sim_total_wp",      "Total WP",           T_SIM, "total_wp",         "",  "int"),
            _f("sim_loops_completed","Loops Completed",   T_SIM, "loops_completed",  "",  "int"),
        ],
    },
    {
        "id": "comms",
        "label": "Comms Link",
        "fields": [
            _f("link_ws_alive",     "WS Alive",           T_LINK, "ws_alive",         "", "bool"),
            _f("link_n_clients",    "WS Clients",         T_LINK, "n_clients",        "", "int"),
            _f("link_last_ping_age","Last Ping Age",      T_LINK, "last_ping_age_s",  "s","float"),
        ],
    },
    {
        "id": "system_monitor",
        "label": "Host / Raspberry",
        "fields": [
            _f("sysmon_cpu_pct",    "CPU Usage",          T_MON, "cpu_percent",   "%",   "float"),
            _f("sysmon_cpu_temp",   "CPU Temperature",    T_MON, "cpu_temp_c",    "°C",  "float"),
            _f("sysmon_ram_used",   "RAM Used",           T_MON, "ram_used_mb",   "MB",  "float"),
            _f("sysmon_ram_total",  "RAM Total",          T_MON, "ram_total_mb",  "MB",  "float"),
            _f("sysmon_ram_pct",    "RAM Used",           T_MON, "ram_percent",   "%",   "float"),
            _f("sysmon_disk_used",  "Disk Used",          T_MON, "disk_used_gb",  "GB",  "float"),
            _f("sysmon_disk_total", "Disk Total",         T_MON, "disk_total_gb", "GB",  "float"),
            _f("sysmon_disk_pct",   "Disk Used",          T_MON, "disk_percent",  "%",   "float"),
            _f("sysmon_uptime",     "Uptime",             T_MON, "uptime_s",      "s",   "float"),
            _f("sysmon_net_rx",     "Net RX",             T_MON, "net_rx_kbps",   "kbps","float"),
            _f("sysmon_net_tx",     "Net TX",             T_MON, "net_tx_kbps",   "kbps","float"),
            _f("sysmon_hostname",   "Hostname",           T_MON, "hostname",      "",    "str"),
            _f("sysmon_os",         "OS",                 T_MON, "os_name",       "",    "str"),
        ],
    },
]


def _index_by_id():
    out = {}
    for g in LOG_FIELD_GROUPS:
        for f in g["fields"]:
            out[f["id"]] = f
    return out


FIELD_INDEX = _index_by_id()
ALL_TOPICS = sorted({f["topic"] for g in LOG_FIELD_GROUPS for f in g["fields"]})


def resolve_path(payload, path):
    """Return the nested value at dot-path inside payload, or None if missing."""
    if payload is None or not path:
        return None
    cur = payload
    for key in path.split("."):
        if isinstance(cur, dict):
            cur = cur.get(key)
        else:
            return None
        if cur is None:
            return None
    return cur
